name: Create candidate repository

on:
  workflow_call:
    inputs:
      candidate_name:
        type: string
        description: "Candidate name"
        required: true
      test_type:
        type: string
        description: "Type of test (js, py, java)"
        required: true

jobs:
  create_repo:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: "theodo-group"
      USER_EMAIL: "joinus@theodo.fr"
      USER_NAME: "theodo-join-us"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define TEMPLATE_REPO env variable
        run: echo "TEMPLATE_REPO=hokla-aphp-${{ inputs.test_type }}" | sed 's/\"//g' >> $GITHUB_ENV

      - name: Define CUSTOM_REPO_NAME env variable
        run: echo "CUSTOM_REPO_NAME=test-hokla-aphp-${{ inputs.test_type }}-${{ inputs.candidate_name }}" | sed 's/\"//g' >> $GITHUB_ENV

      - name: Create a custom repository
        run: |
          curl -f -X POST -H "Authorization: token ${{ secrets.JOIN_US_FORK_INVIT_SECRET }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos \
               -d '{"name":"'"$CUSTOM_REPO_NAME"'", "private":true}'

      - name: Copy the remote repository
        run: |
          git config --global user.email "'"$USER_EMAIL"'"
          git config --global user.name "'"$USER_NAME"'"

          git clone --bare https://x-access-token:${{ secrets.JOIN_US_FORK_INVIT_SECRET }}@github.com/$ORG_NAME/$TEMPLATE_REPO.git $CUSTOM_REPO_NAME.git --single-branch
          cd $CUSTOM_REPO_NAME.git
          git remote remove origin
          git remote add origin https://x-access-token:${{ secrets.JOIN_US_FORK_INVIT_SECRET }}@github.com/$USER_NAME/$CUSTOM_REPO_NAME.git
          git push --mirror
